const SYMBOLS = ["😎", "🔥", "🚀", "🎮", "👾", "🌈", "⭐", "🏆"];
const GRID_SIZE = 16;
const TOTAL_PAIRS = 8;

const MSG = {
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  FLIP_CARD: "FLIP_CARD",
  REQUEST_REMATCH: "REQUEST_REMATCH",
  LEAVE_ROOM: "LEAVE_ROOM",

  ROOM_CREATED: "ROOM_CREATED",
  ROOM_JOINED: "ROOM_JOINED",
  OPPONENT_JOINED: "OPPONENT_JOINED",
  GAME_STARTING: "GAME_STARTING",
  ANIMATION_REVEAL: "ANIMATION_REVEAL",
  ANIMATION_HIDE: "ANIMATION_HIDE",
  ANIMATION_SHUFFLE: "ANIMATION_SHUFFLE",
  GAME_ACTIVE: "GAME_ACTIVE",
  CARD_FLIPPED: "CARD_FLIPPED",
  MATCH_FOUND: "MATCH_FOUND",
  MISMATCH: "MISMATCH",
  GAME_OVER: "GAME_OVER",
  OPPONENT_DISCONNECTED: "OPPONENT_DISCONNECTED",
  ERROR: "ERROR",
  REMATCH_REQUESTED: "REMATCH_REQUESTED",
  REMATCH_ACCEPTED: "REMATCH_ACCEPTED",
};

if (typeof module !== "undefined") {
  module.exports = { SYMBOLS, GRID_SIZE, TOTAL_PAIRS, MSG };
}

export { SYMBOLS, GRID_SIZE, TOTAL_PAIRS, MSG };
